### PR TITLE
feat: Add AnimationCard component

### PR DESCRIPTION
**Pull request by ChunWarayut**
- Implemented AnimationCard component using Framer Motion for smooth animations.
- Utilized useAnimationControls and useMotionValue hooks for animation control.
- Added image scrolling functionality with dynamic speed adjustments.
- Integrated image selection logic based on current scroll position.
- Ensured component is responsive and visually appealing with Next.js Image component.

### CODE REVIEW

**Comment by ChunWarayut** [comment]
@permlap-phola MR ครับ

**Comment by permlap-phola** [comment]
@ChunWarayut 
- [ ] แก้ animation transition กระตุก
- [ ] แก้ onPassPointer

**Comment by permlap-phola** [comment]
@ChunWarayut  ส่งมาก่อนประชุมวันนี้ได้ไหมครับ

**Comment by ChunWarayut** [comment]
@permlap-phola push ไปแล้วครับ

**Pull request merged**
